keycloak:
  postgresql:
    enabled: false  # <--- disable the internal subchart
  externalDatabase:
    host: tributech-postgresql
    user: keycloak
    password: keycloakpassword
    database: keycloakdb
  auth:
    adminUser: admin
    adminPassword: adminpassword
    existingSecret: ""
  proxyAddressForwarding: true
  extraEnv:                    # (or extraEnvVars, depending on chart version)
    - name: PROXY_ADDRESS_FORWARDING
      value: "true"
  ingress:
    enabled: true
    hostname: keycloak.local
    ingressClassName: nginx
    annotations:
      kubernetes.io/ingress.class: nginx
    tls:                     # <‑‑ NEW
      - secretName: keycloak-tls
        hosts:
          - keycloak.local

postgresql:
  auth:
    username: keycloak
    password: keycloakpassword
    database: keycloakdb

pgadmin:
  env:
    email: admin@example.com
    password: adminpassword
  service:
    type: ClusterIP
  ingress:
    enabled: true
    className: nginx
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/ingress.allow-http: "true"
      nginx.ingress.kubernetes.io/use-regex: "true"
    hosts:
      - host: pgadmin.local
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: pgadmin-tls
        hosts:
          - pgadmin.local

website:
  image:
    repository: tributech-website
    tag: local
    pullPolicy: IfNotPresent      # Always if you rebuild a lot
  service:
    type: ClusterIP
    port: 80
  ingress:
    enabled: true
    className: nginx
    hosts:
      - host: website.local
        paths:
          - path: /
            pathType: Prefix
    tls:                          # <-- NEW
      - secretName: website-tls   # must match the secret you just created
        hosts:
          - website.local