keycloak:
  postgresql:
    enabled: false  # <--- disable the internal subchart
  externalDatabase:
    host: tributech-postgresql
    user: keycloak
    password: keycloakpassword
    database: keycloakdb
  auth:
    adminUser: admin
    adminPassword: adminpassword
    existingSecret: ""
  ingress:
    enabled: true
    hostname: keycloak.local
    ingressClassName: nginx
    annotations:
      kubernetes.io/ingress.class: nginx
    tls: false

postgresql:
  auth:
    username: keycloak
    password: keycloakpassword
    database: keycloakdb

pgadmin:
  env:
    email: admin@example.com
    password: adminpassword
  service:
    type: ClusterIP
  ingress:
    enabled: true
    className: nginx
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/ingress.allow-http: "true"
      nginx.ingress.kubernetes.io/use-regex: "true"
    hosts:
      - host: pgadmin.local
        paths:
          - path: /
            pathType: Prefix

