image:
  repository: tributech/website-ui
  tag: latest
  pullPolicy: IfNotPresent

ingress:
  enabled: true
  hostname: website.local

service:
    port: 4200

serviceAccount:
    create: true
    name: ""
autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 80
